const getCompEntryCode = (collected) => {
  if (!collected.length) {
    // no page files, do not generate entry code.
    return '';
  }
  const baseTemplate = `// DO NOT DELETE THIS FILE, auto generated by Fragy.
{import}

export default {
{export}
};
  `.trim();
  const importCode = collected
    .map((item) => {
      return `import ${item.compName} from '${item.relativePath}';`;
    })
    .join('\n');
  const exportCode = collected
    .map((item) => {
      return `  ${item.compName},`;
    })
    .join('\n');

  return baseTemplate.replace('{import}', importCode).replace('{export}', exportCode);
};

module.exports = {
  getCompEntryCode,
};
